---
# tasks file for haproxy
- name: download...
  become: yes
  become_user: root
  get_url:
    url: '{{haproxy_url}}'
    dest: /tmp/{{haproxy_tgz}}
    timeout: '{{haproxy_download_timeout_seconds}}'
    mode: 0644

- name: unarchive...
  become: yes
  become_user: root
  unarchive:
    remote_src: yes
    src: /tmp/{{haproxy_tgz}}
    dest: '{{haproxy_parent_src_dir}}'
    creates: '{{haproxy_src_dir}}'
    
- name: building...
  become: yes
  become_user: root
  command: make -j4 {{haproxy_buildargs}}
  args:
    chdir: '{{haproxy_src_dir}}'
    creates: '{{haproxy_src_dir}}/haproxy'

- name: installing...
  become: yes
  become_user: root
  command: make -j4 install {{haproxy_installargs}}
  args:
    chdir: '{{haproxy_src_dir}}'
    creates: /usr/local/sbin/haproxy

